name: Update NIFTY 50 Data

on:
  schedule:
    - cron: '0 10 * * 1-5'   # Every Mon-Fri at 10:00 UTC = 3:30 PM IST (market close)
  workflow_dispatch:         # Allow manual runs

jobs:
  update-nifty:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yfinance pandas

    - name: Run the update script
      run: python update_nifty.py

    - name: Commit & push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add mydataset.csv
        git commit -m "Update NIFTY 50 data [Auto]" || echo "No changes to commit"
        git push
